In [1]:
# Implementation of FP-Growth Algorithm

# Prepared By : Arjun Mijar
# Roll No.    : 79010160

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth
from IPython.display import display_html

# Function to View Transaction Dataset
def view_transactions(dataset):

    print("\n========== TRANSACTION DATASET ==========\n")

    for i, transaction in enumerate(dataset):
        print(f"T{i+1} : {transaction}")


# Function to Apply FP-Growth Algorithm
def apply_fpgrowth(dataset):

    print("\n========== APPLYING FP-GROWTH ALGORITHM ==========\n")

    # Convert Transactions into Binary Matrix
    te = TransactionEncoder()
    te_data = te.fit(dataset).transform(dataset)

    df = pd.DataFrame(te_data, columns=te.columns_)

    print("Transaction Matrix:\n")
    display_html(df.head())

    # Minimum Support Input
    min_support = float(input("\nEnter Minimum Support Value (Example: 0.3): "))

    # Apply FP-Growth Algorithm
    frequent_itemsets = fpgrowth(df,
                                 min_support=min_support,
                                 use_colnames=True)

    print("\n========== FREQUENT ITEMSETS GENERATED ==========\n")

    if frequent_itemsets.empty:
        print("No Frequent Itemsets Found.")

    else:
        print(frequent_itemsets)


# Menu Function
def menu(dataset):

    print("""
    ========== FP-GROWTH MENU ==========

    1. View Transaction Dataset
    2. Apply FP-Growth Algorithm
    0. Exit
    """)

    option = int(input("Enter Your Option: "))

    while option != 0:

        if option == 1:
            view_transactions(dataset)

        elif option == 2:
            apply_fpgrowth(dataset)

        else:
            print("Please Enter Correct Option.")

        option = int(input("\nEnter Your Option Again: "))

    print("\nProgram Ended Successfully.")


# Main Function
def main():

    # Sample Dataset
    dataset = [

        ['Milk', 'Bread', 'Butter'],

        ['Bread', 'Butter'],

        ['Milk', 'Bread'],

        ['Milk', 'Butter'],

        ['Bread', 'Butter', 'Egg'],

        ['Milk', 'Egg'],

        ['Bread', 'Egg'],

        ['Milk', 'Bread', 'Butter', 'Egg']
    ]

    print("\n========================================")
    print(" IMPLEMENTATION OF FP-GROWTH ALGORITHM ")
    print("========================================")

    print("\nPrepared By : Arjun Mijar")
    print("Roll No.    : 79010160")

    print("\nDo You Want to Start Program? (yes/no)")
    response = input()

    if response.lower() == 'yes':
        menu(dataset)

    else:
        print("\nProgram Terminated.")


# Calling Main Function
main()

========================================
 IMPLEMENTATION OF FP-GROWTH ALGORITHM
========================================

Prepared By : Arjun Mijar
Roll No.    : 79010160

Do You Want to Start Program? (yes/no)

 yes

    ========== FP-GROWTH MENU ==========

    1. View Transaction Dataset
    2. Apply FP-Growth Algorithm
    0. Exit

Enter Your Option:  1

========== TRANSACTION DATASET ==========

T1 : ['Milk', 'Bread', 'Butter']
T2 : ['Bread', 'Butter']
T3 : ['Milk', 'Bread']
T4 : ['Milk', 'Butter']
T5 : ['Bread', 'Butter', 'Egg']
T6 : ['Milk', 'Egg']
T7 : ['Bread', 'Egg']
T8 : ['Milk', 'Bread', 'Butter', 'Egg']

Enter Your Option Again:  2

========== APPLYING FP-GROWTH ALGORITHM ==========

Transaction Matrix:

,Bread,Butter,Egg,Milk
0,True,True,False,True
1,True,True,False,False
2,True,False,False,True
3,False,True,False,True
4,True,True,True,False

Enter Minimum Support Value (Example: 0.3):  0.4

========== FREQUENT ITEMSETS GENERATED ==========

   support         itemsets
0    0.750          (Bread)
1    0.625           (Milk)
2    0.625         (Butter)
3    0.500            (Egg)
4    0.500  (Butter, Bread)

Enter Your Option Again:  2

========== APPLYING FP-GROWTH ALGORITHM ==========

Transaction Matrix:

,Bread,Butter,Egg,Milk
0,True,True,False,True
1,True,True,False,False
2,True,False,False,True
3,False,True,False,True
4,True,True,True,False

Enter Minimum Support Value (Example: 0.3):  0.5

========== FREQUENT ITEMSETS GENERATED ==========

   support         itemsets
0    0.750          (Bread)
1    0.625           (Milk)
2    0.625         (Butter)
3    0.500            (Egg)
4    0.500  (Butter, Bread)

Enter Your Option Again:  0

Program Ended Successfully.